"""ics

Revision ID: 1bb404da212
Revises: 3e117a57d1d
Create Date: 2015-10-27 09:56:32.651429

"""

# revision identifiers, used by Alembic.
revision = '1bb404da212'
down_revision = '3e117a57d1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exportics_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_prodid', sa.String(length=100), nullable=True),
    sa.Column('query', sa.String(length=200), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exportics_configs')
    ### end Alembic commands ###
