"""empty message

Revision ID: 1e504e48396
Revises: db723fd031
Create Date: 2015-10-26 16:19:03.059819

"""

# revision identifiers, used by Alembic.
revision = '1e504e48396'
down_revision = 'db723fd031'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailchimpkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailchimp_key', sa.String(length=100), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailchimpkeys')
    ### end Alembic commands ###
