"""ics config slug

Revision ID: 3315b83e613
Revises: 1bb404da212
Create Date: 2015-10-27 10:03:32.030672

"""

# revision identifiers, used by Alembic.
revision = '3315b83e613'
down_revision = '1bb404da212'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exportics_configs', sa.Column('config_slug', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exportics_configs', 'config_slug')
    ### end Alembic commands ###
