"""suggested events

Revision ID: 3518b5ab170
Revises: 3315b83e613
Create Date: 2015-11-07 13:36:16.179864

"""

# revision identifiers, used by Alembic.
revision = '3518b5ab170'
down_revision = '3315b83e613'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_events',
    sa.Column('title', sa.Unicode(length=256), nullable=False),
    sa.Column('agenda', sa.UnicodeText(), nullable=False),
    sa.Column('social', sa.UnicodeText(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('place', sa.Unicode(length=256), nullable=True),
    sa.Column('when_start', sa.DateTime(), nullable=False),
    sa.Column('when_end', sa.DateTime(), nullable=True),
    sa.Column('only_date', sa.Boolean(), nullable=False),
    sa.Column('registration_url', sa.String(length=500), nullable=True),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.Column('submitter_email', sa.String(length=256), nullable=False),
    sa.Column('secret', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['team'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('secret')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggested_events')
    ### end Alembic commands ###
