"""empty message

Revision ID: 3e117a57d1d
Revises: 824585ca84
Create Date: 2015-10-27 02:13:10.862821

"""

# revision identifiers, used by Alembic.
revision = '3e117a57d1d'
down_revision = '824585ca84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column('web_id', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digests', 'web_id')
    ### end Alembic commands ###
