"""empty message

Revision ID: 3f1d0e7f8f6
Revises: 4411c5cdc99
Create Date: 2015-10-26 22:22:10.895164

"""

# revision identifiers, used by Alembic.
revision = '3f1d0e7f8f6'
down_revision = '4411c5cdc99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailchimpkeys', sa.Column('github_key', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailchimpkeys', 'github_key')
    ### end Alembic commands ###
