"""empty message

Revision ID: 4411c5cdc99
Revises: 1e504e48396
Create Date: 2015-10-26 22:17:53.973614

"""

# revision identifiers, used by Alembic.
revision = '4411c5cdc99'
down_revision = '1e504e48396'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailchimpkeys', sa.Column('templates_uri', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailchimpkeys', 'templates_uri')
    ### end Alembic commands ###
