"""empty message

Revision ID: 5415272c750
Revises: 3f1d0e7f8f6
Create Date: 2015-10-27 01:44:39.125798

"""

# revision identifiers, used by Alembic.
revision = '5415272c750'
down_revision = '3f1d0e7f8f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_name', sa.String(length=100), nullable=True),
    sa.Column('from_email', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('s_list', sa.String(length=20), nullable=True),
    sa.Column('s_list_name', sa.String(length=100), nullable=True),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.String(length=20), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digests')
    ### end Alembic commands ###
