"""empty message

Revision ID: 824585ca84
Revises: 5415272c750
Create Date: 2015-10-27 01:57:56.145325

"""

# revision identifiers, used by Alembic.
revision = '824585ca84'
down_revision = '5415272c750'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column('events_data', postgresql.JSON(), nullable=True))
    op.add_column('digests', sa.Column('events_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('digests', sa.Column('template', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digests', 'template')
    op.drop_column('digests', 'events_ids')
    op.drop_column('digests', 'events_data')
    ### end Alembic commands ###
