"""create events table

Revision ID: aa3723f9c2
Revises: 
Create Date: 2015-10-19 12:03:53.152244

"""

# revision identifiers, used by Alembic.
revision = 'aa3723f9c2'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('social', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('level', sa.Enum('NONE', 'TRAINEE', 'JUNIOR', 'MIDDLE', 'SENIOR', name='level_types'), nullable=True),
    sa.Column('place', sa.String(length=256), nullable=True),
    sa.Column('when_start', sa.DateTime(), nullable=True),
    sa.Column('when_end', sa.DateTime(), nullable=True),
    sa.Column('only_date', sa.Boolean(), nullable=True),
    sa.Column('registration_url', sa.String(length=500), nullable=True),
    sa.Column('special', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    ### end Alembic commands ###
