"""provider added

Revision ID: 33753269335
Revises: 3bfaf7d47e8
Create Date: 2015-10-21 12:29:01.371195

"""

# revision identifiers, used by Alembic.
revision = '33753269335'
down_revision = '3bfaf7d47e8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('provider', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'provider', ['provider'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'provider')
    op.drop_table('provider')
    ### end Alembic commands ###
