"""eventsprovider has key

Revision ID: 37c2263d75c
Revises: 40ad4eef869
Create Date: 2015-10-24 20:12:56.151998

"""

# revision identifiers, used by Alembic.
revision = '37c2263d75c'
down_revision = '40ad4eef869'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('key', sa.String(length=256), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'key')
    ### end Alembic commands ###
