"""empty message

Revision ID: 3bfaf7d47e8
Revises: aa3723f9c2
Create Date: 2015-10-19 15:04:58.131437

"""

# revision identifiers, used by Alembic.
revision = '3bfaf7d47e8'
down_revision = 'aa3723f9c2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'agenda',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('events', 'level',
               existing_type=postgresql.ENUM('NONE', 'TRAINEE', 'JUNIOR', 'MIDDLE', 'SENIOR', name='level_types'),
               nullable=False)
    op.alter_column('events', 'only_date',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('events', 'special',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('events', 'when_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'when_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('events', 'special',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('events', 'only_date',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('events', 'level',
               existing_type=postgresql.ENUM('NONE', 'TRAINEE', 'JUNIOR', 'MIDDLE', 'SENIOR', name='level_types'),
               nullable=True)
    op.alter_column('events', 'agenda',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###
