"""metainfo field

Revision ID: afd908ac2c
Revises: 37c2263d75c
Create Date: 2015-10-25 08:27:53.954461

"""

# revision identifiers, used by Alembic.
revision = 'afd908ac2c'
down_revision = '37c2263d75c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('metainfo', sa.Text(), server_default='{}', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'metainfo')
    ### end Alembic commands ###
